---
schema-version: "1.0"
ci:
  image:
     name: "opensearchstaging/ci-runner:centos7-x64-arm64-jdkmulti-node10.24.1-cypress6.9.1-20211019"
     args: "-e JAVA_HOME=/opt/java/openjdk-11"
build:
  name: OpenSearch
  version: 2.0.0
components:
- name: OpenSearch
  ref: main
  repository: https://github.com/opensearch-project/OpenSearch.git
  checks:
    - gradle:publish
    - gradle:properties:version
schema-version: '1.0'
