---
schema-version: '1.0'
ci:
  image:
    name: opensearchstaging/ci-runner:ci-runner-centos7-v1
    args: -e JAVA_HOME=/opt/java/openjdk-17
build:
  name: OpenSearch
  version: 2.0.0
  qualifier: alpha1
components:
  - name: OpenSearch
    ref: '2.0'
    repository: https://github.com/opensearch-project/OpenSearch.git
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: common-utils
    repository: https://github.com/opensearch-project/common-utils.git
    ref: main
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: job-scheduler
    repository: https://github.com/opensearch-project/job-scheduler.git
    ref: main
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: ml-commons
    repository: https://github.com/opensearch-project/ml-commons.git
    ref: main
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: opensearch-ml-plugin
  - name: k-NN
    repository: https://github.com/opensearch-project/k-NN.git
    ref: main
    platforms:
      - darwin
      - linux
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
