---
schema-version: '1.0'
name: OpenSearch
ci:
  image:
    name: opensearchstaging/ci-runner:ci-runner-centos7-opensearch-build-v3
    args: -e JAVA_HOME=/opt/java/openjdk-20
components:
  - name: cross-cluster-replication
    integ-test:
      topology:
        - cluster_name: leader
          data_nodes: 2
          cluster_manager_nodes: 0
        - cluster_name: follower
          data_nodes: 2
          cluster_manager_nodes: 0
      test-configs:
        - with-security
        - without-security
