---
schema-version: '1.1'
build:
  name: OpenSearch
  version: 3.0.0
ci:
  image:
    name: opensearchstaging/ci-runner:ci-runner-al2-opensearch-build-v1
    args: -e JAVA_HOME=/opt/java/openjdk-21
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: main
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: common-utils
    repository: https://github.com/opensearch-project/common-utils.git
    ref: main
    platforms:
      - linux
      - windows
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: ml-commons
    repository: https://github.com/opensearch-project/ml-commons.git
    ref: main
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: opensearch-ml-plugin
    depends_on:
      - common-utils
  - name: job-scheduler
    repository: https://github.com/opensearch-project/job-scheduler.git
    ref: main
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: opensearch-reports
    repository: https://github.com/opensearch-project/reporting.git
    ref: main
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    depends_on:
      - common-utils
      - job-scheduler
  - name: security
    repository: https://github.com/opensearch-project/security.git
    ref: main
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: performance-analyzer
    repository: https://github.com/opensearch-project/performance-analyzer.git
    ref: main
    platforms:
      - linux
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: opensearch-observability
    repository: https://github.com/opensearch-project/observability.git
    ref: main
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    depends_on:
      - common-utils
  - name: k-NN
    repository: https://github.com/opensearch-project/k-NN.git
    ref: main
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: neural-search
    repository: https://github.com/opensearch-project/neural-search.git
    ref: main
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    depends_on:
      - ml-commons
      - k-NN
  - name: geospatial
    repository: https://github.com/opensearch-project/geospatial.git
    ref: main
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    depends_on:
      - job-scheduler
  - name: anomaly-detection
    repository: https://github.com/opensearch-project/anomaly-detection.git
    ref: main
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    depends_on:
      - common-utils
      - job-scheduler
  - name: cross-cluster-replication
    repository: https://github.com/opensearch-project/cross-cluster-replication.git
    ref: main
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    depends_on:
      - common-utils
  - name: notifications-core
    repository: https://github.com/opensearch-project/notifications.git
    ref: main
    platforms:
      - linux
      - windows
    working_directory: notifications
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: opensearch-notifications-core
    depends_on:
      - common-utils
  - name: notifications
    repository: https://github.com/opensearch-project/notifications.git
    ref: main
    platforms:
      - linux
      - windows
    working_directory: notifications
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: notifications
    depends_on:
      - common-utils
  - name: alerting
    repository: https://github.com/opensearch-project/alerting.git
    ref: main
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: alerting
    depends_on:
      - common-utils
  - name: sql
    repository: https://github.com/opensearch-project/sql.git
    ref: main
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: opensearch-sql-plugin
    depends_on:
      - ml-commons
  - name: asynchronous-search
    repository: https://github.com/opensearch-project/asynchronous-search.git
    ref: main
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
    depends_on:
      - common-utils
  - name: security-analytics
    repository: https://github.com/opensearch-project/security-analytics.git
    ref: main
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
    depends_on:
      - common-utils
  - name: index-management
    repository: https://github.com/opensearch-project/index-management.git
    ref: main
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
    depends_on:
      - common-utils
      - job-scheduler
  - name: flow-framework
    repository: https://github.com/opensearch-project/flow-framework.git
    ref: main
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
