---
schema-version: '1.0'
build:
  name: OpenSearch
  version: 2.10.0
ci:
  image:
    name: opensearchstaging/ci-runner:ci-runner-centos7-opensearch-build-v3
    args: -e JAVA_HOME=/opt/java/openjdk-17
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: 2166b4794e91a5f412e88e2fbb723152afb7ba14
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: common-utils
    repository: https://github.com/opensearch-project/common-utils.git
    ref: 0352c2f4827b0f0239206deb5c3224954d938be3
    platforms:
      - linux
      - windows
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: job-scheduler
    repository: https://github.com/opensearch-project/job-scheduler.git
    ref: e9d36379eedd1bbe9f11bc3e0512f87a8c808b58
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: k-NN
    repository: https://github.com/opensearch-project/k-NN.git
    ref: e43701624f76b7076835395c8374d8c7d42adf47
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: geospatial
    repository: https://github.com/opensearch-project/geospatial.git
    ref: a3da2221d23bf4384020fe234fb97d46548b52c7
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: security
    repository: https://github.com/opensearch-project/security.git
    ref: 6daa697bcd4c73ea411bb765eddf2fac95a29065
    platforms:
      - linux
      - windows
  - name: cross-cluster-replication
    repository: https://github.com/opensearch-project/cross-cluster-replication.git
    ref: dee2f600d214360d32415023a563eeccad103e77
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: ml-commons
    repository: https://github.com/opensearch-project/ml-commons.git
    ref: 5fccfd5c8aa7b4b28afad50b3bc7868623d20deb
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: opensearch-ml-plugin
  - name: neural-search
    repository: https://github.com/opensearch-project/neural-search.git
    ref: 9476d435931315f0b646b3d9c654e80e5a02a828
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: notifications-core
    repository: https://github.com/opensearch-project/notifications.git
    ref: 0a9dfb0c4b54dbe37b304120b02699594bc9572c
    platforms:
      - linux
      - windows
    working_directory: notifications
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: opensearch-notifications-core
  - name: notifications
    repository: https://github.com/opensearch-project/notifications.git
    ref: 0a9dfb0c4b54dbe37b304120b02699594bc9572c
    platforms:
      - linux
      - windows
    working_directory: notifications
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: notifications
  - name: opensearch-observability
    repository: https://github.com/opensearch-project/observability.git
    ref: 4299ace3d55b15e8f6d8c9c8099d9c9b42e38cdf
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: opensearch-reports
    repository: https://github.com/opensearch-project/reporting.git
    ref: 6a9363138ddf039e083c0994e9614319f780b2d5
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: sql
    repository: https://github.com/opensearch-project/sql.git
    ref: ef18b389ebd45f5078a8f7a53cb85eef7d25eae3
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: opensearch-sql-plugin
  - name: asynchronous-search
    repository: https://github.com/opensearch-project/asynchronous-search.git
    ref: a312d9afb1edc7fb4605a70af54f10be4bd054b3
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: anomaly-detection
    repository: https://github.com/opensearch-project/anomaly-detection.git
    ref: bc4d8b18f33e281d863c5719667ce7d52331a9ba
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: alerting
    repository: https://github.com/opensearch-project/alerting.git
    ref: 96518087e35e513c214a3711e8ae62b87dff2254
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: alerting
  - name: security-analytics
    repository: https://github.com/opensearch-project/security-analytics.git
    ref: 0b4bc0817e7267fc5b6a5dc0fdc2b56518a4b1a3
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
  - name: index-management
    repository: https://github.com/opensearch-project/index-management.git
    ref: 062badd9be2a7b0a3d73fd9f7e45f52d5fcdf685
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
  - name: performance-analyzer
    repository: https://github.com/opensearch-project/performance-analyzer.git
    ref: 3ee56fc0d8f7168050fb7d2b066104650aec9710
    platforms:
      - linux
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: custom-codecs
    repository: https://github.com/opensearch-project/custom-codecs.git
    ref: f5a86ffd6037795acd06d27c0b3bc386d9d707ad
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
