---
schema-version: '1.0'
build:
  name: OpenSearch
  version: 2.2.0
ci:
  image:
    name: opensearchstaging/ci-runner:ci-runner-centos7-opensearch-build-v2
    args: -e JAVA_HOME=/opt/java/openjdk-17
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: '2.2'
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: common-utils
    repository: https://github.com/opensearch-project/common-utils.git
    ref: '2.x'
    platforms:
      - linux
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: job-scheduler
    repository: https://github.com/opensearch-project/job-scheduler.git
    ref: '2.2'
    platforms:
      - linux
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: ml-commons
    repository: https://github.com/opensearch-project/ml-commons.git
    ref: '2.2'
    platforms:
      - linux
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: opensearch-ml-plugin
  - name: performance-analyzer
    repository: https://github.com/opensearch-project/performance-analyzer.git
    ref: '2.2'
    platforms:
      - linux
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: security
    repository: https://github.com/opensearch-project/security.git
    ref: '2.2'
    platforms:
      - linux
  - name: geospatial
    repository: https://github.com/opensearch-project/geospatial.git
    ref: '2.2'
    platforms:
      - linux
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: k-NN
    repository: https://github.com/opensearch-project/k-NN.git
    ref: '2.2'
    platforms:
      - linux
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: cross-cluster-replication
    repository: https://github.com/opensearch-project/cross-cluster-replication.git
    ref: '2.2'
    platforms:
      - linux
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: notifications-core
    repository: https://github.com/opensearch-project/notifications.git
    ref: '2.2'
    platforms:
      - linux
    working_directory: notifications
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: opensearch-notifications-core
  - name: notifications
    repository: https://github.com/opensearch-project/notifications.git
    ref: '2.2'
    platforms:
      - linux
    working_directory: notifications
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: notifications
  - name: anomaly-detection
    repository: https://github.com/opensearch-project/anomaly-detection.git
    ref: '2.2'
    platforms:
      - linux
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: asynchronous-search
    repository: https://github.com/opensearch-project/asynchronous-search.git
    ref: '2.2'
    platforms:
      - linux
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: alerting
    repository: https://github.com/opensearch-project/alerting.git
    ref: '2.2'
    platforms:
      - linux
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: alerting
  - name: index-management
    repository: https://github.com/opensearch-project/index-management.git
    ref: '2.2'
    platforms:
      - linux
    checks:
      - gradle:properties:version
  - name: sql
    repository: https://github.com/opensearch-project/sql.git
    ref: '2.2'
    platforms:
      - linux
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: opensearch-sql-plugin
  - name: opensearch-observability
    repository: https://github.com/opensearch-project/observability
    ref: '2.2'
    platforms:
      - linux
    working_directory: opensearch-observability
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: dashboards-reports
    repository: https://github.com/opensearch-project/dashboards-reports.git
    ref: '2.2'
    platforms:
      - linux
    working_directory: reports-scheduler
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
