---
schema-version: '1.0'
name: OpenSearch
ci:
  image:
    name: opensearchstaging/ci-runner:ci-runner-al2-opensearch-build-v1
    args: -e JAVA_HOME=/opt/java/openjdk-21
components:
  - name: alerting
    integ-test:
      test-configs:
        - with-security
        - without-security
      additional-cluster-configs:
        plugins.destination.host.deny_list:
          - 10.0.0.0/8
          - 127.0.0.1
    bwc-test:
      test-configs:
        - with-security
  - name: anomaly-detection
    integ-test:
      build-dependencies:
        - job-scheduler
      test-configs:
        - with-security
        - without-security
    bwc-test:
      test-configs:
        - with-security
  - name: flow-framework
    integ-test:
      test-configs:
        - with-security
        - without-security
  - name: asynchronous-search
    integ-test:
      test-configs:
        - with-security
        - without-security
    bwc-test:
      test-configs:
        - with-security
  - name: cross-cluster-replication
    integ-test:
      topology:
        - cluster_name: leader
          data_nodes: 2
        - cluster_name: follower
          data_nodes: 2
      test-configs:
        - with-security
        - without-security
  - name: geospatial
    integ-test:
      test-configs:
        - with-security
        - without-security
  - name: index-management
    integ-test:
      build-dependencies:
        - job-scheduler
      test-configs:
        - with-security
        - without-security
      additional-cluster-configs:
        path.repo:
          - /tmp
    bwc-test:
      test-configs:
        - with-security
  - name: k-NN
    integ-test:
      test-configs:
        - with-security
        - without-security
  - name: ml-commons
    integ-test:
      test-configs:
        - with-security
        - without-security
  - name: neural-search
    integ-test:
      test-configs:
        - with-security
        - without-security
  - name: notifications
    working-directory: notifications
    integ-test:
      test-configs:
        - with-security
        - without-security
    bwc-test:
      test-configs:
        - with-security
  - name: opensearch-observability
    integ-test:
      test-configs:
        - with-security
        - without-security
    bwc-test:
      test-configs:
        - with-security
  - name: opensearch-reports
    integ-test:
      test-configs:
        - with-security
        - without-security
  - name: security
    integ-test:
      test-configs:
        - with-security
  - name: security-analytics
    integ-test:
      test-configs:
        - with-security
        - without-security
  - name: sql
    integ-test:
      test-configs:
        - with-security
        - without-security
      additional-cluster-configs:
        script.context.field.max_compilations_rate: 1000/1m
        plugins.query.datasources.encryption.masterkey: 4fc8fee6a3fd7d6ca01772e5
    bwc-test:
      test-configs:
        - with-security
  - name: custom-codecs
    integ-test:
      test-configs:
        - with-security
        - without-security
  - name: skills
    integ-test:
      test-configs:
        - with-security
        - without-security
  - name: query-insights
    integ-test:
      test-configs:
        - with-security
        - without-security
