---
name: automatic-merges

on:
  workflow_run:
    # If new workflows triggered on pull request are added, they should be added to this list
    workflows:
      - Link Checker
      - yaml-lint
      - dockerfile-lint
      - groovy-tests
      - manifests
      - python-tests
    types: completed

jobs:
  automatic-merge-manifests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: find-triggering-pr
        uses: peternied/find-triggering-pr@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: peternied/discerning-merger@v1
        if: steps.find-triggering-pr.outputs.pr-number != null
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.find-triggering-pr.outputs.pr-number }}
          allowed-authors: |
            dependabot
            opensearch-trigger-bot
            peterzhuamazon
            bbarani
            gaiksaya
            rishabh6788
            zelinh
            jordarlu
            prudhvigodithi
            Divyaasm
            dblock
            tianleh
            peternied
          allowed-files: |
            manifests/*/*.yml
