name: WhiteSource Vulnerability Scan

on:
#  schedule:
#    - cron: '30 10 * * *'
  repository_dispatch:
    types: [check-vulnerability-whitesource]
  push:
    branches: [sreekarj_scan]

jobs:
  Provision-Runners:
    name: Provision-Runners
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_WSS_EC2_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_WSS_EC2_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Setting up runner
        run: |
          RUNNERS="opensearch-wss-scan"
          scripts/setup_runners.sh run $RUNNERS ${{ secrets.OPENSEARCH_RELEASE_BOT_PUBLIC_PRIVATE_READ_WRITE_TOKEN }} ami-0bd968fea932935f4

  whitesource-vulnerability-scan:
    needs: [Provision-Runners]
    name: WhiteSource Vulnerability Scan
    runs-on: [self-hosted, Linux, X64, opensearch-wss-scan]
    outputs:
      mail_content_output: ${{ steps.vulnerability_scan.outputs.mail_content }}
    strategy:
      fail-fast: false
      matrix:
        java: [14]
        go-version: [1.14]
    steps:
      - uses: actions/checkout@v1
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
#      - uses: actions/checkout@v1
#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_MAVEN_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_MAVEN_SECRET_ACCESS_KEY }}
#          aws-region: us-west-2
      - name: Vulnerability Scan
        id: vulnerability_scan
        env:
          wss_apikey: ${{ secrets.WSS_API_KEY }}
        run: |
          export PATH=$JAVA_HOME:$PATH
          cd  tools/vulnerability-scan
          sudo yum install -y maven
          wget -q https://services.gradle.org/distributions/gradle-6.7-bin.zip
          sudo mkdir /opt/gradle
          sudo unzip -d /opt/gradle gradle-6.7-bin.zip
          wget -qO - https://rpm.nodesource.com/setup_10.x | sudo bash -
          sudo yum install -y nodejs-10.23.1
          sudo npm install --global yarn@1.22.10
          export PATH=$PATH:/opt/gradle/gradle-6.7/bin
          gradle -v; mvn -v; node -v; npm -v; yarn -v
          # This step is needed to avoid build failures in few plugins
          # No ETA on when this dependency can be removed 
          git clone -b 1.0 https://github.com/opensearch-project/OpenSearch.git
          cd OpenSearch ; gradle publishToMavenLocal -Dbuild.version_qualifier=beta1 -Dbuild.snapshot=false
          gradle publishToMavenLocal -Dbuild.version_qualifier=rc1 -Dbuild.snapshot=false
          gradle publishToMavenLocal  -Dbuild.snapshot=false ; cd ..
          #git clone https://github.com/opensearch-project/job-scheduler.git
          #cd job-scheduler; gradle publishToMavenLocal -Dbuild.snapshot=false; cd ..
          #git clone https://github.com/opensearch-project/common-utils.git
          #cd common-utils; gradle publishToMavenLocal; cd ..
          #git clone https://github.com/opensearch-project/alerting.git
          #cd alerting; gradle :alerting-notification:publishToMavenLocal; cd ..
          # Run Whitesource scan
          ./wss-scan.sh
          echo ::set-output name=mail_content::$(cat output.md)
          cat whitesource/*/*

  CleanUp-Runners:
    needs: [whitesource-vulnerability-scan]
    if: always()
    name: CleanUp-Runners
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_WSS_EC2_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_WSS_EC2_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Removing runner
        run: |
          RUNNERS="opensearch-wss-scan"
          scripts/setup_runners.sh terminate $RUNNERS ${{ secrets.OPENSEARCH_RELEASE_BOT_PUBLIC_PRIVATE_READ_WRITE_TOKEN }}
