---
name: License Header Checker

on: [push, pull_request]

jobs:
  license-header-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Add License Header
        uses: kt3k/license_checker@v1.0.6
