---
name: manifests

on:
  pull_request:
    types: [ labeled ]

jobs:
  list-manifests11:
    if: ${{ github.repository == 'gaiksaya/opensearch-build' && github.event.label.name == 'manifest-ci-check' }}
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get changed manifest files
        uses: tj-actions/changed-files@v39
        id: list-changed-manifests
        with:
          files: manifests/**/opensearch*.yml
          json: true
          quotepath: false
          dir_names: false

      - name: Set unique changed manifests as matrix
        id: set-matrix
        run: echo "matrix={\"manifest\":${{ steps.list-changed-manifests.outputs.all_changed_files }}}" >> "$GITHUB_OUTPUT"


  manifest-checks-jdk11:
    needs: list-manifests11
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.9
      JDK_VERSION: 11
    strategy:
      matrix:
        manifest: ${{ fromJson(needs.list-manifests11.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - name: Set Up JDK ${{ env.JDK_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JDK_VERSION }}
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Pipenv and Dependencies
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: OpenSearch Manifests
        run: |-
          ./ci.sh ${{ matrix.manifest }} --snapshot

  manifest-checks-jdk17:
    needs: list-manifests17
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.9
      JDK_VERSION: 17
    strategy:
      matrix:
        manifest: ${{ fromJson(needs.list-manifests17.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - name: Set Up JDK ${{ env.JDK_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JDK_VERSION }}
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Pipenv and Dependencies
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: OpenSearch Manifests
        run: |-
          ./ci.sh ${{ matrix.manifest }} --snapshot
