---
name: manifests-ci-check

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'manifests/**/*.yml'
      - '!manifests/templates/**/'
      - 'legacy-manifests/**/*.yml'

jobs:
  list-changed-manifests:
    if: ${{ github.repository == 'opensearch-project/opensearch-build' }}
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get changed manifest files
        uses: tj-actions/changed-files@e9772d140489982e0e3704fea5ee93d536f1e275
        id: list-changed-manifests
        with:
          files: manifests/**/opensearch*.yml
          json: true
          quotepath: false
          dir_names: false

      - name: Set unique changed manifests as matrix
        id: set-matrix
        run: echo "matrix={\"manifest\":${{ steps.list-changed-manifests.outputs.all_changed_files }}}" >> "$GITHUB_OUTPUT"

  manifest-checks:
    needs: [list-changed-manifests]
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.9
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.list-changed-manifests.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - name: Check JDK Version
        run: |
          java_version=`cat ${{ matrix.manifest }} | yq -r .ci.image.args | grep -Eo '[0-9]+' || echo ''`
          echo $java_version
          echo "JAVA_VERSION=$java_version" >> "$GITHUB_ENV"
      - name: Set Up JDK ${{ env.JAVA_VERSION }}
        if: ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Pipenv and Dependencies
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: OpenSearch Manifests
        run: |-
          ./ci.sh ${{ matrix.manifest }} --snapshot
