name: manifests

on:
  push:
    paths:
      - 'manifests/**/*.yml'
      - '!manifests/templates/**/'
  pull_request:
    paths:
      - 'manifests/**/*.yml'
      - '!manifests/templates/**/'
  schedule:
    - cron: 0 0 * * *

jobs:
  list-changed-manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get changed manifest files
        uses: tj-actions/changed-files@v39
        id: list-changed-manifests
        with:
          separator: ' '
      - name: Set unique changed manifests as matrix
        id: set-matrix
        run: |
          echo "matrix=$(${{ steps.list-changed-manifests.outputs.all_changed_files }} | awk -F/ '{if($2>2)print$0}' | jq -R -s -c 'split(" ")[:-1]') " >> GITHUB_OUTPUT
          
        #run: echo "matrix=$(ls manifests/**/opensearch*.yml | awk -F/ '{if($2>2)print$0}' | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
  
  manifest-checks-jdk11:
    needs: list-changed-manifests
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.9
      JDK_VERSION: 11
    strategy:
      matrix:
        manifest: ${{ needs.list-changed-manifests.outputs.matrix && fromJson(needs.list-changed-manifests.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK ${{ env.JDK_VERSION }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JDK_VERSION }}
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Pipenv and Dependencies
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: OpenSearch Manifests
        run: |-
          ./ci.sh ${{ matrix.manifest }} --snapshot

  manifest-checks-jdk17:
    needs: list-changed-manifests
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.9
      JDK_VERSION: 17
    strategy:
      matrix:
        manifest: ${{ needs.list-changed-manifests.outputs.matrix && fromJson(needs.list-changed-manifests.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK ${{ env.JDK_VERSION }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JDK_VERSION }}
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Pipenv and Dependencies
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: OpenSearch Manifests
        run: |-
          ./ci.sh ${{ matrix.manifest }} --snapshot


